export const products = [
  {
    id: 1,
    title: "Bolo no pote",
    price: 7000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i1.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
  {
    id: 2,
    title: "Macarrão",
    price: 3000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i1.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
  {
    id: 3,
    title: "Pincho com Kikuanga",
    price: 4000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i2.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
  {
    id: 4,
    title: "Sopa",
    price: 8000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i3.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
  {
    id: 5,
    title: "Bolo no pote",
    price: 7000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i1.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
  {
    id: 6,
    title: "Macarrão",
    price: 3000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i2.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
  {
    id: 7,
    title: "Pincho com Kikuanga",
    price: 4000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i3.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
  {
    id: 8,
    title: "Sopa",
    price: 8000,
    validation: 4.5,
    imageUrl: require("@/assets/image/i1.png"),
    avatarUrl: "@/assets/image/a1.png",
  },
];
