/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(auth)'}/signin` | `/screens/signin`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(auth)'}/signup` | `/screens/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/api` | `/screens/api`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/cart` | `/screens/cart`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/chatbot` | `/screens/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}` | `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/settings` | `/screens/settings`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(detail)'}/[id]` | `/screens/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(auth)'}/signin` | `/screens/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(auth)'}/signup` | `/screens/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(main)'}/api` | `/screens/api`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(main)'}/cart` | `/screens/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(main)'}/chatbot` | `/screens/chatbot`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(main)'}` | `/screens`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(main)'}/settings` | `/screens/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/screens${'/(detail)'}/[id]` | `/screens/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/screens${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/screens/signin${`?${string}` | `#${string}` | ''}` | `/screens${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/screens/signup${`?${string}` | `#${string}` | ''}` | `/screens${'/(main)'}/api${`?${string}` | `#${string}` | ''}` | `/screens/api${`?${string}` | `#${string}` | ''}` | `/screens${'/(main)'}/cart${`?${string}` | `#${string}` | ''}` | `/screens/cart${`?${string}` | `#${string}` | ''}` | `/screens${'/(main)'}/chatbot${`?${string}` | `#${string}` | ''}` | `/screens/chatbot${`?${string}` | `#${string}` | ''}` | `/screens${'/(main)'}${`?${string}` | `#${string}` | ''}` | `/screens${`?${string}` | `#${string}` | ''}` | `/screens${'/(main)'}/settings${`?${string}` | `#${string}` | ''}` | `/screens/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(auth)'}/signin` | `/screens/signin`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(auth)'}/signup` | `/screens/signup`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/api` | `/screens/api`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/cart` | `/screens/cart`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/chatbot` | `/screens/chatbot`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}` | `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/screens${'/(main)'}/settings` | `/screens/settings`; params?: Router.UnknownInputParams; } | `/screens${'/(detail)'}/${Router.SingleRoutePart<T>}` | `/screens/${Router.SingleRoutePart<T>}` | { pathname: `/screens${'/(detail)'}/[id]` | `/screens/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
